server.port=8081
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DeliveryDB;encrypt=false

spring.datasource.username=sa
spring.datasource.password=tu_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true